# Generated by Django 2.0.7 on 2019-12-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191228_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('1', 'Very good'), ('2', 'Good'), ('3', 'Normal'), ('4', 'Bad')], max_length=1, verbose_name='请为本条信息评级')),
            ],
        ),
    ]
