# Generated by Django 2.0.7 on 2019-12-29 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191229_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Account'),
        ),
    ]
